remote_theme		: cotes2020/jekyll-theme-chirpy
url					: https://hub.newspectrum.dev/
base_url			: ""
#repository			: "github.com/NewSpectrum/NewSpectrum-Home"
title				: "New Spectrum Home"
title_separator		: "-"