remote_theme		: "mmistakes/jekyll-theme-basically-basic@1.4.5"
url					: https://hub.newspectrum.dev/
base_url			: ""
#repository			: "github.com/NewSpectrum/NewSpectrum-Home"
title				: "New Spectrum Home"
title_separator		: "-"
skin				: night

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji